site_name: Android 性能优化手册
site_url: https://android-performance-optimization.github.io/
site_description: 专注于 Android 性能优化领域，分享基础知识，实战方案，学习路线，技术动态等资源

# Repository
repo_name: 'android-performance-optimization'
repo_url: 'https://github.com/android-performance-optimization/homepage'

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: 'zh'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - search:
      lang: ja
  - git-revision-date-localized
  
# Page tree
nav:
  - 首页:
    - 简介: index.md
    - 如何参与: intro/htc.md
  - 学习资源: resource/index.md
  - 筑基手册:
    - 程序员的自我修养:
      - foundation/self-cultivation/elf-file-detail.md
      - foundation/self-cultivation/static-link.md
      - foundation/self-cultivation/elf-load.md
      - foundation/self-cultivation/dynamic-link.md
      - foundation/self-cultivation/memory.md
      - foundation/self-cultivation/system-call.md
    - 深入实践 Kotlin 元编程:
      - foundation/kotlin-meta-programming/meta-programming-basic.md
      - foundation/kotlin-meta-programming/meta-data-introduction.md
      - foundation/kotlin-meta-programming/runtime-reflect.md
      - foundation/kotlin-meta-programming/code-generate.md
      - foundation/kotlin-meta-programming/symbol-process.md
      - foundation/kotlin-meta-programming/code-static-analyse.md
      - foundation/kotlin-meta-programming/compiler-extension.md
      - foundation/kotlin-meta-programming/meta-programming-debug.md
    - Kolin 编译器学习:
      - foundation/kotlin-compiler-learn/learning-resource.md
    - 重学 C/C++:
      - foundation/restudy-c-cpp/environment-config.md
      - foundation/restudy-c-cpp/quick-start.md
      - foundation/restudy-c-cpp/basic-concept.md
      - foundation/restudy-c-cpp/data-type.md
      - foundation/restudy-c-cpp/statement.md
      - foundation/restudy-c-cpp/operators-and-expressions.md
      - foundation/restudy-c-cpp/pointer.md
      - foundation/restudy-c-cpp/function.md
      - foundation/restudy-c-cpp/array.md
      - foundation/restudy-c-cpp/char-and-string.md
      - foundation/restudy-c-cpp/struct-and-union.md
      - foundation/restudy-c-cpp/dynamic-memory.md
      - foundation/restudy-c-cpp/struct-and-pointer.md
      - foundation/restudy-c-cpp/advanced-pointer.md
    - Android 系统基础:
      - foundation/framework/activity-start.md
    - 实用工具系列:
      - foundation/tools/native-hook.md
  - 实战手册:
    - 编译优化:
      - practical/compile/compile-acceleration.md
      - practical/compile/now-in-android.md
    - 代码质量优化:
      - practical/code-quality/kotlin-detekt.md
    - 稳定性优化:
      - practical/stability/airbag.md
    - 速度优化:
      - practical/speed/json-serialization-speed.md
      - practical/speed/kcp-gson-moshi.md
    - 内存优化:
      - practical/memory/memory-usage-analyse.md
  - 技术月报:
    - 2024:
      - news/2024/news-2024-05.md
      - news/2024/news-2024-04.md
      - news/2024/news-2024-03.md
      - news/2024/news-2024-02.md
      - news/2024/news-2024-01.md
    - 2023:
      - news/2023/news-2023-12.md
      - news/2023/news-2023-11.md
      - news/2023/news-2023-10.md
      - news/2023/news-2023-09.md
      - news/2023/news-2023-08.md
      - news/2023/news-2023-07.md