name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Setup mkdocs Plugin
        run: pip install mkdocs-material
      
      - name: Build mkdocs Page
        run: mkdocs build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:android-performance-optimization/android-performance-optimization.github.io.git
          SQUASH_HISTORY: "false"
          BRANCH:  main
          FOLDER: public
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}